### ISSUE TITLE
Error while initializing app TypeError: Cannot read property 'models' of undefined

### ISSUE THREAD

**Issue by Kleemer** [vuex-orm/vuex-orm#180]
Hi,
I was using version 0.24.4 and decided to upgrade to 0.25.3. However, it seems that the buildMorphOne function is failing, for any kind of Morph relationship defined.

My Schema is simple :
```
import { Model } from '@vuex-orm/core'
export default class Answer extends Model {
  static get entity() {
    return 'answers'
  }
  static fields() {
    return {
      id: this.attr(null),
      answerable_id: this.attr(null),
      answerable_type: this.attr(null),
      answerable: this.morphTo('answerable_id', 'answerable_type')
    }
  }
}
```
And here is the error I got :
<img width="875" alt="screen shot 2018-06-28 at 12 29 57 pm" src="https://user-images.githubusercontent.com/5712094/42056648-be9c1a56-7acf-11e8-9bcc-1b562d7672d0.png">

Sorry to bother you again, and thanks again for your help !

**Comment by bradstewart** [comment]
I'm hitting this as well, for seemingly any kind of relationship.

**Comment by kiaking** [comment]
Hi! Sorry for the inconvenience! I have released Vuex ORM 0.25.4, could you try using it and see it fixes the issue?
https://github.com/vuex-orm/vuex-orm/releases/tag/v0.25.4

I haven't tackle this issue but I've refactored the code where the error message shows, and it might have fixed this issue.

**Comment by Kleemer** [comment]
It did fix the issue for me which is great ! But the issue of #174 is still not resolved in my case, in     HasOne.prototype.attach = function (key, record, data), key is null sometimes and this throw an error ... Would you want me to re-open the issue to give you the informations you could need ?

**Comment by kiaking** [comment]
@Kleemer Thanks for the report! Let me check on this. Maybe I made regression...

**Comment by kiaking** [comment]
@Kleemer Hi! I've checked and currently the following test is passing. Maybe I'm missing something here. Could you give me the data you are trying to insert?

```js
class User extends Model {
  static entity = 'users'

  static fields () {
    return {
      id: this.attr(null),
      phone: this.hasOne(Phone, 'user_id')
    }
  }
}

class Phone extends Model {
  static entity = 'phones'

  static fields () {
    return {
      id: this.attr(null),
      user_id: this.attr(null)
    }
  }
}

it('can create data when the has one relation is `null`', () => {
  const store = createStore([{ model: User }, { model: Phone }])

  store.dispatch('entities/users/create', {
    data: {
      id: 1,
      phone: null
    }
  })

  const expected = createState({
    users: {
      '1': { $id: 1, id: 1, phone: null }
    },
    phones: {}
  })

  expect(store.state.entities).toEqual(expected)
})
```

**Comment by Kleemer** [comment]
Sure, my models look like this : 
```
class User extends Model {
  static entity = 'users'

  static fields () {
    return {
      id: this.attr(null),
      active_user_phone: this.hasOne(Phone, 'user_id')
    }
  }
}

class UserPhone extends Model {
  static entity = 'userPhones'

  static fields () {
    return {
      id: this.attr(null),
      user_id: this.attr(null)
    }
  }
}
```
and the data I am trying to insert :
```
[
  {
    active_user_phone : {
      id: "10",
      user_id: "1"
    },
    id : "1"
  },
  {
    active_user_phone : null,
    id : "2"
  }
]
```

Can it be because I am trying to insert a list, with some of them having the attribute as null and some of them not ? Because when I try to insert just the one that is not working in a list it seems that it works ! I will try again later to confirm what I am saying.

**Comment by kiaking** [comment]
Aha, maybe it is...? I'm making a quite big change on relationship resolving logics so I'll come back and check again when I'm finished!

**Comment by kiaking** [comment]
@Kleemer I've reproduced this and fixed at #190! You were right, it some times fail if you have data that have mixed relation!

**Comment by Kleemer** [comment]
Amazing ! I'm sure everything will work as soon as you release this 😄Thanks for your help !

**Comment by kiaking** [comment]
This is now resolved by Vuex ORM 0.25.5 🔥  Thank you all for your report and feed back!
