### ISSUE TITLE
Class constructor Token cannot be invoked without 'new' after upgrading from 0.33.0 to 0.35.0

### ISSUE THREAD

**Issue by cwirz** [vuex-orm/vuex-orm#544]
When i insert a new object im getting the error message: Class constructor Token cannot be invoked without 'new'

`        Token.insert({
          data: {
            token: parsed.jwt,
          }
        })
`

```
export default class Token extends Model {
  static entity = 'tokens'
  static fields () {
    return {
      token: this.string(null),
    }
  }
}

```

**Comment by cuebit** [comment]
Doesn't sound like a Vuex ORM issue. What's your babel setup?

**Comment by clementdubois** [comment]
Same issue here, seems to appear in jest tests.

I use babel-jest and my babel config is only using the @vue/app presets

**Comment by steven0811** [comment]
Same here, I using Nuxt.js with Nuxt.js's default babel setup.

**Comment by kiaking** [comment]
Wow, seems like many people having trouble with this...? Can anyone create a minimal reproduction for this?

**Comment by HamishBrindle** [comment]
Ya I'm only getting this is during Mocha tests.

Here are some relevant packages we're using:
```
"dependencies": {
    "@vuex-orm/core": "^0.35.1",
    "core-js": "^2.6.5",
    "vue": "^2.6.10",
    "vue-router": "^3.0.3",
    "vuex": "^3.0.1",
  },
  "devDependencies": {
    "@babel/core": "^7.6.4",
    "@babel/node": "^7.6.3",
    "@babel/plugin-proposal-nullish-coalescing-operator": "^7.8.3",
    "@babel/plugin-proposal-optional-chaining": "^7.8.3",
    "@vue/cli-plugin-babel": "^3.11.0",
    "@vue/cli-plugin-unit-mocha": "^4.0.5",
    "@vue/test-utils": "^1.0.0-beta.29",
    "babel-core": "7.0.0-bridge.0",
    "babel-plugin-dynamic-import-node": "^2.2.0",
    "chai": "^4.2.0",
    "jsdom": "^15.2.0",
    "jsdom-global": "^3.0.2",
    "mocha": "^6.2.2",
    "mocha-webpack": "^1.1.0",
    "vue-template-compiler": "^2.5.21",
  },
```

Our `babel.config.js`
```
module.exports = {
  presets: [
    '@vue/app',
  ],
  plugins: [
    '@babel/plugin-proposal-optional-chaining',
    '@babel/plugin-proposal-nullish-coalescing-operator',
  ],
  env: {
    test: {
      plugins: [
        'dynamic-import-node',
      ],
    },
  },
};
```

I looked around, and it does seem like a Babel issue, and again, only experiencing this running Mocha tests.

**Comment by haversnail** [comment]
Likewise: also seeing this error in a Nuxt.js SSR app (and also using their default Babel setup). Specifically, this is occurring when `await`ing creation of a record in Nuxt's `fetch` hook. (FYI, also can't seem to successfully create a record from the `fetch` hook as it's depicted [in the example app](https://github.com/vuex-orm/vuex-orm-examples-nuxt/blob/master/pages/index.vue#L39), which is what led me to try waiting for the promise to resolve in the first place. Suspect this may also be related to #475.)

**Comment by cuebit** [comment]
This is primarily a server side issue. It’s **not** a client issue.

### Advisory
Please use [v0.34.1](https://github.com/vuex-orm/vuex-orm/releases/tag/v0.34.1) if this is a critical issue. 

### Reproduction
To reproduce this issue, install the [Vuex ORM Nuxt Example App](https://github.com/vuex-orm/vuex-orm-examples-nuxt), update to the latest plugin release and observe the terminal output. 

### Trace
A functional update was introduced in 0.35 that binds the user model to utilise the database it was registered with. It seems ES5 doesn’t bode well with runtime ES6 class extensions so the build process for Vuex ORM will need to be revised.

**Comment by cuebit** [comment]
Additionally, there may be alternatives to mitigate this issue without the use of runtime class extensions. One example would be to set the database instance on the model itself which also adds to scalability.

**Comment by Vercoutere** [comment]
Same thing here using Vue.js Server-Side Rendering.
Error occurs at insert of a new model in my store.

`this.$db().model('companies').insert({data: normalizeJson(company)})`

Retrieval works without issue.

**Comment by supercodepoet** [comment]
We are having the same issue using this library in an Electron app. Downgrading to 0.34.1 fixed the issue. It appears to happen because of the `createBindingModel `call in:

```
const entity: Entity = {
      name: model.entity,
      base: model.baseEntity || model.entity,
      model: this.createBindingModel(model),
      module
    }
```

The transpiled Typescript that is in `vuex-orm.esm.js` looks like:

```
Database.prototype.createBindingModel = function (model) {
        var database = this;
        var c = /** @class */ (function (_super) {
            __extends(class_1, _super);
            function class_1() {
                return _super !== null && _super.apply(this, arguments) || this;
            }
            class_1.store = function () {
                return database.store;
            };
            return class_1;
        }(model));
        Object.defineProperty(c, 'name', { get: function () { return model.name; } });
        return c;
    };
```

With the line  `return _super !== null && _super.apply(this, arguments) || this;` throwing the error about not using `new` with the class constructor.

**Comment by kiaking** [comment]
Thanks to @cuebit, this should be fixed with Vuex ORM 0.36.1! 🔥 
https://github.com/vuex-orm/vuex-orm/releases/tag/v0.36.1

**Comment by 2-5** [comment]
I still have this error with Vuex ORM 0.36.3 (and TypeScript 3.8.3 as transpiler):

```
vuex-orm.esm.js:5852 Uncaught (in promise) TypeError: Class constructor Instrument cannot be invoked without 'new'
    at new proxy (vuex-orm.esm.js:5852)
    at Query.push../node_modules/@vuex-orm/core/dist/vuex-orm.esm.js.Query.hydrate (vuex-orm.esm.js:5271)
    at vuex-orm.esm.js:5299
    at Object.map (vuex-orm.esm.js:952)
    at Query.push../node_modules/@vuex-orm/core/dist/vuex-orm.esm.js.Query.mapHydrateRecords (vuex-orm.esm.js:5299)
    at Query.push../node_modules/@vuex-orm/core/dist/vuex-orm.esm.js.Query.insertRecords (vuex-orm.esm.js:4949)
    at Query.push../node_modules/@vuex-orm/core/dist/vuex-orm.esm.js.Query.persistRecords (vuex-orm.esm.js:5153)
    at vuex-orm.esm.js:5138
    at Array.reduce (<anonymous>)
    at Query.push../node_modules/@vuex-orm/core/dist/vuex-orm.esm.js.Query.persist (vuex-orm.esm.js:5134)
```

**Comment by sdevore** [comment]
@kiaking I think there is a regression in this between 36.1 and 36.4 it should be reopened.  Or if there is another workaround for this to work could it be added to documentation

**Comment by adrianmoreno2** [comment]
Same here: 
```
TypeError: Class constructor Model cannot be invoked without 'new'
    at new StoreUser (StoreUser.ts?d596:60)
    at new StoreUser (eval at createBindingModel (vuex-orm.esm.js:1), <anonymous>:5:16)
    at Query.hydrate (vuex-orm.esm.js?6ff8:5113)
    at eval (vuex-orm.esm.js?6ff8:5139)
    at Object.map (vuex-orm.esm.js?6ff8:963)
    at Query.mapHydrateRecords (vuex-orm.esm.js?6ff8:5139)
    at Query.insertRecords (vuex-orm.esm.js?6ff8:4796)
    at Query.insertOrUpdateRecords (vuex-orm.esm.js?6ff8:4960)
    at Query.persistRecords (vuex-orm.esm.js?6ff8:4998)
    at eval (vuex-orm.esm.js?6ff8:4979)
```

-  "@vuex-orm/core": "^0.36.4"
-  "@vuex-orm/plugin-axios": "^0.9.4"
